name: Build, Test, and Deploy Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout repository
    - uses: actions/checkout@v4

    # Step 2: Install Trivy
    - name: Install Trivy
      run: |
        sudo apt-get update -y
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update -y
        sudo apt-get install -y trivy


    # Step 3: Build Docker Image
    - name: Build Docker Image
      run: |
        APP_NAME="container-k8s-hub"
        APP_VERSION="2.0.0"
        tag="${APP_NAME}:${APP_VERSION}"
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        echo "${{ github.repository }}"
